### ISSUE TITLE
设置文件路径无效

### ISSUE THREAD

**Issue by KiWiLss** [mymdeep/deepimg#1]

**Comment by mymdeep** [comment]
最近有些忙，没过来看，请问您是怎么使用的

**Comment by KiWiLss** [comment]
就像下面这样,随便测试的
 ImageConfigure configure = new ImageConfigure();
        configure.directoryname = "android";//目录名
        configure.filename = "beautiful.jpg";//文件名

        DeepImage deepImage = new DeepImage(this, R.drawable.image5,configure);
        File file = deepImage.asFile();

**Comment by KiWiLss** [comment]
加了目录名,file就为null.不加目录名,只加文件名就可以

**Comment by mymdeep** [comment]
首先感谢您的使用，设置目录的时候请使用如下代码（需要设置路径的）： 
 ImageConfigure configure = new ImageConfigure();
                configure.directoryname = "/sdcard/android";//目录名
                configure.filename = "beautiful.jpg";//文件名

**Comment by mymdeep** [comment]
首先感谢您的使用，设置目录的时候请使用如下代码（需要设置路径的）： 
 ImageConfigure configure = new ImageConfigure();
                configure.directoryname = "/sdcard/android";//目录名
                configure.filename = "beautiful.jpg";//文件名

**Comment by KiWiLss** [comment]
好的,thank you!
